# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: BACKEND CICD

on:
  push:
    branches: [ master, dev ]
  pull_request:
    branches: [ master, dev ]

jobs:
  publish:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v1
      with:
        java-version: '11'
        distribution: 'adopt'
    - name: Build image with Maven
      run: mvn spring-boot:build-image
    - name: Tag Image
      run: docker tag fs_project:0.0.1 ${{secrets.DOCKERHUB_USERNAME}}/fs_backend
    - name: Docker login
      env: 
        DOCKER_USER: ${{secrets.DOCKERHUB_USERNAME}}
        DOCKER_SECRET: ${{secrets.DOCKERHUB_SECRET}}
      run: |
        docker login -u $DOCKER_USER -p $DOCKER_SECRET
    - name: push image
      run: |
        docker push $DOCKER_USER/fs_backend
